name: Publish Docker image

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/eventy-blog-webmob

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: cr.yandexcloud.kz
          username: ${{ secrets.YANDEX_REGISTRY_USERNAME }}
          password: ${{ secrets.YANDEX_REGISTRY_OAUTH }}

      - name: Build and push Docker image
        run: |
          docker build -t eventy/blog-webmob:$(echo ${{ steps.meta.outputs.version }} | cut -c 2-) .
          docker tag "eventy/blog-webmob:$(echo ${{ steps.meta.outputs.version }} | cut -c 2-)" cr.yandexcloud.kz/crksp0ersei7pfkuvqsc/blog-webmob:$(echo ${{ steps.meta.outputs.version }} | cut -c 2-)
          docker tag "eventy/blog-webmob:$(echo ${{ steps.meta.outputs.version }} | cut -c 2-)" cr.yandexcloud.kz/crksp0ersei7pfkuvqsc/blog-webmob:latest
          docker push cr.yandexcloud.kz/crksp0ersei7pfkuvqsc/blog-webmob:$(echo ${{ steps.meta.outputs.version }} | cut -c 2-)
          docker push cr.yandexcloud.kz/crksp0ersei7pfkuvqsc/blog-webmob:latest